### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by manojkal** [alexanderGugel/wsd#10]
Could you please help with the below issue. I am not able to connect.
Thanks

 wsd -url=ws://localhost:1337/ws
connecting to ws://localhost:1337/ws from http://localhost/...
panic: websocket.Dial ws://localhost:1337/ws: dial tcp [::1]:1337: getsockopt: connection refused
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4c29b1]

goroutine 1 [running]:
panic(0x73df40, 0xc82000e100)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
golang.org/x/net/websocket.(*Conn).Close(0x0, 0x0, 0x0)
        /home/Host1/app/src/golang.org/x/net/websocket/websocket.go:236 +0xd1
panic(0x725260, 0xc8200aeb00)
        /usr/lib/golang/src/runtime/panic.go:443 +0x4e9
main.main()
        /home/Host1/app/src/github.com/alexanderGugel/wsd/main.go:126 +0x8c7

**Comment by anaaChacon** [comment]
#2633

**Comment by anaaChacon** [comment]
#14 +1

**Comment by anaaChacon** [comment]
@manojkal I am still testing to try to fix this, because the problem slows me down.
The test I have done and it has worked well for me at the moment is:

**Case success**

At the moment my disconnection problem seems to be solved by launching the application with the following command:
`ionic cordova run android --address XXX.XXX.X.XXX --port 5555 --livereload`

**XXX.XXX.X.XXX** -> **It is equal to my IP address**

This ip is the one that my wifi assigns, on the mobile I am connected to the same wifi as on the PC and also on the PC I am also connected by cable.

But I am not sure what is really happening, it seems to be a problem with localhost, because I had to define the address, my address
